services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: swissmedical-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pacientes-app-bd
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_URL: jdbc:postgresql://db:5432/swissmedical-db
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  db_data: