services:

  db:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p$${DATABASE_PASSWORD}"]
      timeout: 20s
      retries: 10
      interval: 10s

  app:
    build: .
    container_name: crud-pacientes-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${DATABASE_DRIVER}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM: ${DATABASE_PLATFORM}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${DDL_AUTO}
