version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysqlpacientes
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_IN}:${DB_PORT_OUT}"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: pacientes-app
    ports:
      - "${API_PORT_IN}:${API_PORT_OUT}"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SERVER_PORT: ${API_PORT_IN}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:${DB_PORT_OUT}/${DB_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

volumes:
  mysql_data: