version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysqlpacientes
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: paciente
      MYSQL_USER: rootpacientes
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  app:
    build: .
    container_name: pacientes-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/paciente?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: rootpacientes
      SPRING_DATASOURCE_PASSWORD: admin
    restart: unless-stopped

volumes:
  mysql_data:
